#users:
#  path: /emdata/users.json

users:
  path: C:/emdata/users.json

org:
  eclipse:
    store:
      auto-start: true
      root: com.github.michalperlak.flashcards.cards.model.Cards
      storage_directory: _data
      rest:
        enabled: true
